name: Publish Release
on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create changelogs
      id: changelogs
      uses: heineiuo/create-changelogs@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.changelogs.outputs.changelogs }}
        draft: false
        prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}